CREATE SCHEMA E_STORE; 

CREATE TABLE E_STORE.PRODUCT (
	PRODUCT_ID int auto_increment,
    NAME VARCHAR(30),
    MAKE VARCHAR(30),
    MODEL VARCHAR(30),
    CATEGORY VARCHAR(20),
    STOCK int,
    DESCRIPTION VARCHAR(50),
    PRICE decimal(10,2),
	primary key(PRODUCT_ID)
);